src/objects/Gift_Card_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>External_Store_Id__c</fullName>
        <label>External Store Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Gift Card Transaction</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Gift Card Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Card Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Store_Number__c</fullName>
        <label>Store Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestGiftCardTransaction.cls
@isTest
public class TestGiftCardTransaction{
    static testMethod void testunit() {
        
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         ProfileId = pf.Id,
                         Store_Number__c=1
                        ); 
        
        
        insert uu;
        
        Gift_Card_Transaction__c GCT = new Gift_Card_Transaction__c(External_Store_Id__c=1);
        insert(GCT);
    }
}